services:

  traefik:
    image: "traefik:v3.0"
    container_name: ${COMPOSE_PROJECT_NAME}-traefik
    restart: unless-stopped
    profiles: [ dev, prod ]
    ports:
      # open 80 and 443 ports
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      # Traefik Dashboard ON
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${APP_URL:?Set APP_URL in .env}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.tls=true"
    networks:
      - net

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        PHP_WEBSERVER: ${PHP_WEBSERVER:-nginx}
        PHP_VERSION: ${PHP_VERSION:-8.2}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    profiles: [ dev, prod ]
    restart: unless-stopped
    tty: true
    environment:
      # Info: https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification
      - SSL_MODE=off
      - AUTORUN_ENABLED=false
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=50M
      - PHP_UPLOAD_MAX_FILE_SIZE=50M
      - PHP_MAX_EXECUTION_TIME=60
      - PHP_OPCACHE_ENABLE=1
      - APACHE_DOCUMENT_ROOT=${APP_WEBROOT:-/var/www/html}
      - NGINX_WEBROOT=${APP_WEBROOT:-/var/www/html}
    volumes:
      # mount the project directory to /var/www/html
      # APP_PATH - is required!
      - ${APP_PATH:?Set APP_PATH in .env}:/var/www/html
      - ./nginx/custom.conf:/etc/nginx/server-opts.d/custom.conf
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.php.loadbalancer.server.port=8080"  # port of php-fpm
      - "traefik.http.routers.php.rule=Host(`${APP_URL:?Set APP_URL in .env}`)"
      - "traefik.http.routers.php.entrypoints=http,https"
      - "traefik.http.routers.php.tls=true"

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    profiles: [ dev, prod ]
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?Set MYSQL_ROOT_PASSWORD in .env}
      - MYSQL_USER=${DB_USERNAME:?Set DB_USERNAME in .env}
      - MYSQL_PASSWORD=${DB_PASSWORD:?Set DB_PASSWORD in .env}
      - MYSQL_DATABASE=${DB_DATABASE:?Set DB_DATABASE in .env}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD:?Set MYSQL_ROOT_PASSWORD in .env}" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    profiles: [ dev, prod ]
    volumes:
      - redis:/data
    networks:
      - net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    profiles: [ dev, prod ]
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
      - "traefik.http.routers.pma.rule=Host(`pma.${APP_URL:?Set APP_URL in .env}`)"
      - "traefik.http.routers.pma.entrypoints=http,https"
      - "traefik.http.routers.pma.tls=true"

  node:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-node
    profiles: [ dev ]
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    volumes:
      # APP_PATH - is required!
      - ${APP_PATH:?Set APP_PATH in .env}:/var/www
    working_dir: /var/www
    networks:
      - net

volumes:
  redis:

networks:
  net:
