services:
  traefik:
    command:
      - "--configFile=/etc/traefik/traefik-prod.yml"
    labels:
      # Let's Encrypt SSL Cert
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"

      # middleware with basic auth
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH}"  # format user:hashedpassword
    volumes:
      # mount the production configuration file
      - "./traefik/config/traefik-prod.yml:/etc/traefik/traefik-prod.yml:ro"

      # mount the Let's Encrypt certificate storage'
      - "letsencrypt:/letsencrypt"

  php:
    build:
      target: production
    labels:
      # Let's Encrypt SSL Cert
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.routers.php.tls.certresolver=le"

  mysql:
    # Access only via localhost.
    ports:
      - '127.0.0.1:${DB_PORT:-3306}:3306'

  phpmyadmin:
    labels:
      # Let's Encrypt SSL Cert
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.tls.certresolver=le"

      # Middleware with basic auth and IP whitelist
      - "traefik.http.routers.pma.middlewares=pma-auth"
      - "traefik.http.middlewares.pma-auth.basicauth.users=${TRAEFIK_AUTH_PMA}"
      - "traefik.http.routers.pma.middlewares=pma-auth,pma-ipwhitelist"
      - "traefik.http.middlewares.pma-ipwhitelist.ipwhitelist.sourcerange=${ALLOWED_IP_PMA:-0.0.0.0/0}" # если ALLOWED_IP_PMA не задана то будет открыт доступ со всех адресов

volumes:
  letsencrypt:
