services:
  traefik:
    command:
      - "--configFile=/etc/traefik/traefik-prod.yml" # Используем внешний конфигурационный файл Traefik
    labels:
      # Let's Encrypt SSL Cert
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"

      # Добавляем middleware с базовой авторизацией
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH}"  # Формат: user:hashedpassword
    volumes:
      # Монтируем config
      - "./traefik/config/traefik-prod.yml:/etc/traefik/traefik-prod.yml:ro"

      # для хранения SSL сертификатов
      - "letsencrypt:/letsencrypt"

  php:
    build:
      target: production
    labels:
      # Let's Encrypt SSL Cert
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.routers.php.tls.certresolver=le"

  mysql:
    # Доступ через SSH-туннель на localhost сервера.
    ports:
      - '127.0.0.1:${DB_PORT:-3306}:3306'

  phpmyadmin:
    labels:
      # Let's Encrypt SSL Cert
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.tls.certresolver=le"

      # Middleware для базовой авторизации и ограничения по IP
      - "traefik.http.routers.pma.middlewares=pma-auth"
      - "traefik.http.middlewares.pma-auth.basicauth.users=${TRAEFIK_AUTH_PMA}"
      - "traefik.http.routers.pma.middlewares=pma-auth,pma-ipwhitelist"
      - "traefik.http.middlewares.pma-ipwhitelist.ipwhitelist.sourcerange=${ALLOWED_IP_PMA:-0.0.0.0/0}" # если ALLOWED_IP_PMA не задана то будет открыт доступ со всех адресов

volumes:
  letsencrypt:
