services:

  traefik:
    image: "traefik:v3.0"
    container_name: ${COMPOSE_PROJECT_NAME}-traefik
    restart: unless-stopped
    profiles: [ dev, prod ]
    ports:
      # Открываем 80 и 443 порты на хосте
      - "80:80"
      - "443:443"
    volumes:
      # Traefik следит за событиями Docker через сокет
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      # Включить маршрутизацию Traefik для самого себя (Dashboard)
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${APP_URL}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=http,https"
      - "traefik.http.routers.traefik.tls=true"
    networks:
      - net

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        PHP_WEBSERVER: ${PHP_WEBSERVER:-nginx}
        PHP_VERSION: ${PHP_VERSION:-8.2}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    profiles: [ dev, prod ]
    restart: unless-stopped
    tty: true
    environment:
      # https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification
      - SSL_MODE=off
      - AUTORUN_ENABLED=false
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=50M
      - PHP_UPLOAD_MAX_FILE_SIZE=50M
      - PHP_MAX_EXECUTION_TIME=60
      - PHP_OPCACHE_ENABLE=1
      - APACHE_DOCUMENT_ROOT=${APP_WEBROOT:-/var/www/html}
      - NGINX_WEBROOT=${APP_WEBROOT:-/var/www/html}
    volumes:
      # Монтируем проект внутрь контейнера
      # APP_DIR - должна быть задана обязательно! Если не задана выводим - Set APP_DIR in .env!
      - ../${APP_DIR:?Set APP_DIR in .env}:/var/www/html
      - ./nginx/custom.conf:/etc/nginx/server-opts.d/custom.conf
    depends_on:
      - mysql
      - redis
    networks:
      - net
    labels:
      # Включаем Traefik
      - "traefik.enable=true"
      - "traefik.http.services.php.loadbalancer.server.port=8080"  # Указываем внутренний порт контейнера
      - "traefik.http.routers.php.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.php.entrypoints=http,https"
      - "traefik.http.routers.php.tls=true"

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    profiles: [ dev, prod ]
    tty: true
    environment:
      # Основные настройки MySQL
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    profiles: [ dev, prod ]
    volumes:
      - redis:/data
    networks:
      - net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    profiles: [ dev, prod ]
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - net
    labels:
      # Включаем Traefik
      - "traefik.enable=true"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
      - "traefik.http.routers.pma.rule=Host(`pma.${APP_URL}`)"
      - "traefik.http.routers.pma.entrypoints=http,https"
      - "traefik.http.routers.pma.tls=true"

  node:
    image: node:18-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-node
    profiles: [ dev ]
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    volumes:
      # APP_DIR - должна быть задана обязательно! Если не задана выводим - Set APP_DIR in .env!
      - ../${APP_DIR:?Set APP_DIR in .env}:/var/www
    working_dir: /var/www
    networks:
      - net

# Определяем именованные тома для хранения данных
volumes:
  redis:

# Общая сеть между всеми сервисами
networks:
  net:
