# https://github.com/serversideup/docker-php

############################################
# Base Image
############################################

# Choose any image
#FROM serversideup/php:8.2-fpm-nginx as base
FROM serversideup/php:8.2-fpm-apache as base

# Switch to root so we can do root things
USER root

# Install extensions with apt (example)
#RUN set -ex; \
#    apt update; \
#    apt install -y php8.2-pgsql nano

# Install extensions with docker-php-ext-install (example)
#RUN set -ex; \
#    apt update -q && \
#    apt install -q -y libpq-dev && \
#    docker-php-ext-install pdo_pgsql pgsql bcmath


# Install extensions with install-php-extensions
# https://serversideup.net/open-source/docker-php/docs/customizing-the-image/installing-additional-php-extensions
# Supported PHP extensions wich you can install by install-php-extensions here - https://github.com/mlocati/docker-php-extension-installer
RUN set -ex; \
    apt update; \
    install-php-extensions intl PDO json gd exif bcmath


############################################
# Production Image
############################################

# Copy our app into the Docker image
FROM base as production

# Установка рабочей директории
WORKDIR /var/www/html

ARG USER_ID
ARG GROUP_ID

COPY --chown=$USER_ID:$GROUP_ID $APP_PATH .

# composer install (example)
#RUN composer install --no-cache --ansi --no-interaction \
#    && composer dump-autoload -o

# Drop back to our unprivileged user
USER www-data
